name: 'setup-shfmt-action'
description: 'Install shfmt and cache it for GitHub Actions'
author: 'pollenJP'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  version:
    description: 'shfmt version'
    required: true
    default: 'latest'
  github_token:
    description: 'GitHub token'
    required: false
    default: ''
runs:
  using: node20
  main: dist/index.js
