name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
        version: [latest, 3.10.0]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./
        with:
          version: ${{ matrix.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Detect cached
        uses: ./ # Check using cache by watching logs
        with:
          version: ${{ matrix.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: check
        run: shfmt --version
  test-no-token:
    name: GitHub Actions Test (No Token)
    # GitHub API rate limit exceeds when using macos because of https://github.com/actions/runner-images/issues/602
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: latest
